# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KSYLiveUIDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

   pod 'libksygpulive/libksygpulive_265',       :path => '../'
   # KSYGPUResource 为基础版本的图片资源, 包含了美颜滤镜必须依赖的图片
   pod 'libksygpulive/KSYGPUResource',          :path => '../' 
   pod 'Masonry'
   pod 'JSONModel'
   pod 'SDWebImage'
   pod 'Toast'
   pod 'Bugly'
   # YYImage 仅demo中用于导入gif和apng的格式的图片用到了
   # 不需要支持这些格式的话,不需要添加YYImage的依赖
   pod 'YYImage'
   pod 'YYCache'
   pod 'ZipArchive'
end
